# This workflow will set a number or reviewers depending on the labels
name: Label Reviews
# Trigger the workflow on pull requests
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  pull_request_review:
    types:
      - submitted
      - edited
      - dismissed
jobs:
  require-reviewers:
    # Optional: skip check if no relevant label is present
    # This needs to be kept in sync with the labels being checked
    if: ${{ contains(github.event.pull_request.labels.*.name, 'Affects Balance') || contains(github.event.pull_request.labels.*.name, 'ongoing freeze') }}
    runs-on: ubuntu-latest
    steps:
      - name: Label requires reviews
        uses: BlueWeabo/label-requires-reviews-action@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN}}
        with:
          github_token: ${{ secrets.GH_TOKEN}}
          # define which PR labels require how many aprroving reviewers
          rules_yaml: |-
            affects balance: 3 
            freeze: 99
